### ISSUE TITLE
Necessary thing in the update

### ISSUE THREAD

**Issue by colemad** [vytdev/minecraft-acode-plugin#1]
1. Add editor .js  for gametest API
2. Add editor ui/gui
3. Add editor entity, block and etc. creater

> Yes, perhaps the requests are difficult to execute, but in my opinion this is the most important thing that should be in the utility for convenient creation and edition of addons

**Comment by vytdev** [comment]
Thanks @colemad! I'll do my best to add those features. Your feedback means a lot! 😊

**Comment by colemad** [comment]
In any case, it is extremely convenient now. Looking forward to improving what is already good

**Comment by vytdev** [comment]
Thank you for your excitement about the features you've mentioned! I'm not always focused on blocks, entities, and JSON UI, but I'm definitely planning to work on them for the plugin. I want to ensure they are done right, which might take some time. Your understanding and patience mean a lot to me! Thanks for your support! :blush:

**Comment by colemad** [comment]
In fact, they are a little similar to each other, so this is a great functionality that can be done

**Comment by vytdev** [comment]
Hi there! I was imagining how it'll look after implementation. Wondering where to place the button for creating new items, blocks, UI, animations, recipes, and more, hehe. What do you think? Would it be okay to have a new button that opens a dropdown with all these options? I'd really appreciate your input before I start implementing. Thanks a bunch!

**Comment by colemad** [comment]
The easiest thing in my opinion is to make a bind, for example Ctrl+M, which will open a menu with a choice of what you need, but I was talking about a simple syntax for creating, for example, a tooltip or highlighting, you made it complicated but it also sounds good

**Comment by vytdev** [comment]
Hi @colemad! Quick check – when you mentioned 'simple syntax for tooltips and highlighting', were you thinking of something like auto-suggestions for Minecraft json? I might've got a bit mixed up, thinking about the model editor with graphics, like .bridge. My bad if it's a bit confusing! Your thoughts mean a lot, thanks a bunch!

**Comment by colemad** [comment]
Yes, that’s what I meant, but if you can do something more functional, that’s also good, but I was thinking about the minimum

**Comment by vytdev** [comment]
Sorry for the earlier confusion. I haven't started on it because I haven't explored Minecraft blocks yet, and I took a break from coding last week to rest. It might take me a while, maybe weeks or months. School also demands my time. I'll do my best to tackle it soon. Thanks for understanding!
